apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: server-node
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31000